export const endPointApi = {
  SIGNUP: "auth/signup",
  LOGIN: "auth/login",
  PRODUCT: "/medicines",
  MEDICINE: "medicine",
  ARTICLE: "articles",
  ORDERS: "orders",
  ORDER: "order",
  USERS: "users",
  UPLOAD_IMAGE: "image",
  CATEGORY_MEDICINE: "category-medicine",
  BRANCH: "branch",
  BRANCHES: "branches",
  VOUCHER: "voucher",
};
